export const ADD_CATEGORIES = "ADD_CATEGORIES";

export const SET_AUTH_TRUE = "SET_AUTH_TRUE";
export const SET_AUTH_FALSE = "SET_AUTH_FALSE";

export const ADD_USERS = "ADD_REQUESTS";

export const ADD_REQUESTS = "ADD_REQUESTS";
export const GET_ALL_REQUESTS = "GET_ALL_REQUESTS";
export const GET_ALL_REQUESTS_STARTED = "GET_ALL_STARTED";
export const GET_ALL_REQUESTS_SUCCESS = "GET_ALL_SUCCESS";
export const GET_ALL_REQUESTS_FAILURE = "GET_ALL_FAILURE";
export const SET_WORKER_ID = "SET_WORKER_ID";
export const SET_WORKER_ID_SUCCESS = "SET_WORKER_ID_SUCCESS";
export const SET_WORKER_ID_FAILURE = "SET_WORKER_ID_FAILURE";
export const SET_REQUEST_RESOLVED_SUCCESS = "SET_REQUEST_RESOLVED_SUCCESS";
export const SET_REQUEST_RESOLVED_FAILURE = "SET_REQUEST_RESOLVED_FAILURE";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAILURE = "DELETE_REQUEST_FAILURE";